Tictactoe
BenjaminGarza/TicTacToe pull request #1
Opened 2020-08-11 20:22 UTC by BenjaminGarza

2020-08-12 13:14 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-12 13:14 UTC, bellom commented on .eslintrc.json
> +{
Opps, we have some changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/javascript)
You need to fix linter's error.
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-08-12 13:14 UTC, bellom commented on .stickler.yml
> +      - 'dist/*'
**NOTE:** Microverse has moved on to Github actions for continuous deployment please use that instead of stickler. 
![image](https://user-images.githubusercontent.com/31897434/85197008-14353c00-b2d6-11ea-932b-d3a0ab291c2a.png)

https://github.com/microverseinc/linters-config/tree/master/javascript

2020-08-12 13:14 UTC, bellom commented on README.md
> +![](screenshot.png)
kindly add a live link, am pretty sure have seen you guys making use of live link before 😄

2020-08-12 13:14 UTC, bellom commented on index.html
> +      <input type='text' id='player1' placeholder='Player 1'>
**To Improve;**
I think you should change the placeholder content, let's it clear for users that they can type in their names.

`type in your name` => not bad right?

2020-08-12 13:14 UTC, bellom commented on script.js
> +  ];
Opps, after checking for win, I think the game should end right?

In our case here, it is possible to have two winners, 🤦 

![image](https://user-images.githubusercontent.com/31897434/90015196-2f9e4100-dca0-11ea-9e96-11e4c9da6c93.png)

2020-08-13 13:56 UTC, rOluochKe requested changes
Hello @BenjaminGarza and @Sick-Carlito 
### Well done, you are almost there :clap: Just one fix
- [ ] Separate app logic from dom manipulation
![applogic](https://user-images.githubusercontent.com/8114528/90143086-d90b3280-dd85-11ea-9ba4-b8b4a34f8880.png)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

2020-08-13 13:57 UTC, rOluochKe commented on script.js
> +};
### Separate game dom manipulation from logic

2020-08-13 13:58 UTC, rOluochKe commented on script.js
> +
### Separate game dom manipulation from logic

2020-08-14 15:14 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

I am so sorry for having you requested for another `CRR` I already drafted the comment but I refresh the page due to internet issue, I was surprised when I saw DOM changes 😄 .

```
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/
```

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-17 14:44 UTC, merged